name: Auto Merge PR

on:
  workflow_call:
    secrets:
      AUTO_MERGE_TOKEN:
        required: true

jobs:
  auto-merge:
    name: Auto Merge Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run Auto Merge Action
        uses: Adamantine-guild/.github/.github/actions/auto-merge@main
        with:
          AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
