name: 'Auto Merge Automation'
description: 'Production-ready reusable GitHub Action to validate and auto-merge PRs.'
author: 'Adamantine-guild'

inputs:
  AUTO_MERGE_TOKEN:
    description: 'Fine-grained Personal Access Token for GitHub authentication'
    required: true

runs:
  using: 'node20'
  main: 'index.js'
